controllers:
    resource: '../src/Controller/'
    type: attribute

login_check:
    path: /api/login_check
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /
        permanent: false
